### ISSUE TITLE
2012 Presidential Election

### ISSUE THREAD

**Issue by scottpham** [openelections/openelections-results-nc#1]
Hi there,

Does this repo have presidential results? I'm looking at the 2012 general election file, `20121106__nc__general__precinct__raw`, but there are only state results in it.

**Comment by dwillis** [comment]
You are right, and we'll get federal results in asap. Thanks for catching this!

**Comment by dwillis** [comment]
Ok, I've updated the 2012 general election precinct file so that it includes both presidential and congressional results.
