### ISSUE TITLE
SQL scripts 

### ISSUE THREAD

**Issue by kflanagan** [openelections/openelections-results-nc#3]
I have created a few SQL scripts to add the most recent year's data to MySQL databases.  Some of the data type info is likely to be incorrect, as I created them all as varchar, but that's an exercise for improvement. I'd like to add them, but it's not allowed.

**Comment by dwillis** [comment]
Hi @kflanagan - you can make a pull request if you like.

**Comment by kflanagan** [comment]
@dwillis It's likely that I'm missing some fundamental use things here, I'm a real newcomer to github, but I can't see that I can create a branch to add things to, so I can't do a pull request to merge those files in to the master branch.  The directions I found indicated that I could create a branch via the web, that's not available, I created a local branch but can't --set-upstream.  Access denied.  Do you have a reference I should be reading?

**Comment by dwillis** [comment]
Hey @kflanagan  - I think the best route is for you to fork this repository so you have your own version of it, commit your changes and then you should be able to create a pull request. Some guides:

https://help.github.com/articles/about-forks/
https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/
